### ISSUE TITLE
Refactor webpack.config

### ISSUE THREAD

**Issue by cirocosta** [AEHO/mango#11]
We're almost building the whole project for each new example that is added as an entrypoint. We could take advantage of webpack's 'commons' generation. Explore this alternative later.

**Comment by MateusZitelli** [comment]
I don't know if it's possible to don't recompile the whole project each time that some entry point is added, because the Webpack must be reloaded to load the new entry schema. But actually after the first build the webpack-dev-server just rebuild what is needed after some code change.

The use of commons chunks plugin is interesting to group in their own chunk, code that are heavily reused, like vendors.

**Comment by cirocosta** [comment]
Yep, i was suggesting the second part of your answer (the commons chunk plugin). 
There's just sooo much in common between both of the chunks;
![mango11](https://cloud.githubusercontent.com/assets/3574444/8019914/cbc10c46-0c3c-11e5-8ec6-1e1649bd1b7e.png)

Have you ever used that plugin @MateusZitelli  ?

**Comment by MateusZitelli** [comment]
Yep, one thing that we can do is something like this:

``` js
new CommonsChunkPlugin({
  name: "example-commons",
  filename: "example-commons.js",
  minChunks: 2,
  chunks: ["01-square", "02-cuber"],
})
```

Which will create a chunck with all the modules that are loaded by the chunks specified.
What do you think?

**Comment by cirocosta** [comment]
I think that's fine :dart: Would you mind adding this and checking whether it goes nicely? :+1:

**Comment by MateusZitelli** [comment]
Ok, I'll do this :+1:

**Comment by cirocosta** [comment]
![dimitri](http://i1042.photobucket.com/albums/b424/Ronanfalcon/Net%20Images/GIF/Dimitri-gif.gif)

**Comment by MateusZitelli** [comment]
Huston have a problem, when the new common chunk is created the modules from mango aren't duplicated, so we get something like this:
![2015-06-06-143703_1920x1980_scrot](https://cloud.githubusercontent.com/assets/201472/8020704/8ff403cc-0c59-11e5-8ee1-9d05fe4d32e3.png)

**Comment by MateusZitelli** [comment]
I think that a solution would not use the common chunk plugin, but instead import in the example the whole mongo module like a vendor, don't you think so?

**Comment by cirocosta** [comment]
But what you achieved isn't the expected? I mean, those modules that were being compiled twice are now going all into `example-commons` (compiling only once)

**Comment by MateusZitelli** [comment]
Yep, but now those modules are in `example-commons.js` not in `mongo.js`. In the case of distribution of the Mango as a lib those modules will not be present.

**Comment by cirocosta** [comment]
aah, sure, now i understood. I agree with you
